export const GOLDEN_CASES = Object.freeze([
  {
    id: 'TR-GOLD-001',
    title: 'Vollmacht ohne Unterschrift',
    client_label: 'Nguyễn A. · synthetisch',
    category: 'Mandantenaufnahme',
    state: 'INCOMPLETE',
    urgency: 'NORMAL',
    vn_original: 'Tôi đã tải lên giấy ủy quyền và hợp đồng thuê nhà. Tôi không chắc còn thiếu giấy tờ gì.',
    de_translation: 'Ich habe die Vollmacht und den Mietvertrag hochgeladen. Ich bin nicht sicher, welche Unterlagen noch fehlen.',
    summary: 'Vollmacht vorhanden, aber nicht unterschrieben. Mietvertrag vollständig.',
    open_points: ['Unterschrift auf Vollmacht fehlt'],
    documents: [
      ['Personalausweis', 'vollständig'],
      ['Vollmacht', 'Unterschrift fehlt'],
      ['Mietvertrag', 'vollständig']
    ],
    next_action: 'Fehlende Unterschrift beim Mandanten anfordern',
    baseline_seconds: 420,
    review_seconds: 85,
    avoided_followups: 1,
    timeline: ['Einladung geöffnet', '2FA bestätigt', '3 Dokumente zugeordnet', 'Vollmacht: Unterschrift fehlt', 'Rückfrage vorbereitet']
  },
  {
    id: 'TR-GOLD-002',
    title: 'Nebenkostenabrechnung unvollständig',
    client_label: 'Trần B. · synthetisch',
    category: 'Dokumentation',
    state: 'INCOMPLETE',
    urgency: 'NORMAL',
    vn_original: 'Đây là bảng chi phí phụ năm 2025. Tôi đã chụp tất cả các trang mà tôi có.',
    de_translation: 'Hier ist die Nebenkostenabrechnung 2025. Ich habe alle Seiten fotografiert, die ich habe.',
    summary: 'Seiten 1, 2 und 4 vorhanden. Seite 3 fehlt.',
    open_points: ['Seite 3 der Nebenkostenabrechnung fehlt'],
    documents: [['Nebenkosten 2025', 'Seite 3 fehlt'], ['Mietvertrag', 'vollständig']],
    next_action: 'Fehlende Seite 3 beim Mandanten anfordern',
    baseline_seconds: 360,
    review_seconds: 70,
    avoided_followups: 1,
    timeline: ['Upload empfangen', 'Dateien Quarantäne → clean', 'Seitenfolge geprüft', 'Seite 3 fehlt', 'Rückfrage vorbereitet']
  },
  {
    id: 'TR-GOLD-003',
    title: 'Datum widersprüchlich',
    client_label: 'Lê C. · synthetisch',
    category: 'Formalien',
    state: 'REVIEW',
    urgency: 'HIGH',
    vn_original: 'Tôi nhận được thư vào ngày 03.09.2026.',
    de_translation: 'Ich habe das Schreiben am 03.09.2026 erhalten.',
    summary: 'Schreiben nennt 03.09.; Aktennotiz enthält 02.09. Quelle muss verglichen werden.',
    open_points: ['Datum 03.09. vs. 02.09.'],
    documents: [['Schreiben', '03.09.2026'], ['Aktennotiz', '02.09.2026']],
    next_action: 'Beide Quellen vergleichen und korrektes Datum übernehmen',
    baseline_seconds: 300,
    review_seconds: 95,
    avoided_followups: 0,
    timeline: ['Schreiben extrahiert', 'Aktennotiz gelesen', 'Datumswiderspruch erkannt', 'Manuelle Entscheidung erforderlich']
  },
  {
    id: 'TR-GOLD-004',
    title: 'Frist im Schreiben erkannt',
    client_label: 'Phạm D. · synthetisch',
    category: 'Frist',
    state: 'READY',
    urgency: 'HIGH',
    vn_original: 'Tôi nhận được thư này hôm nay và không hiểu thời hạn trong thư.',
    de_translation: 'Ich habe dieses Schreiben heute erhalten und verstehe die darin genannte Frist nicht.',
    summary: 'Explizite Antwortfrist erkannt. Keine automatische Fristübernahme; Bao prüft Quelle.',
    open_points: [],
    documents: [['Behördenschreiben', 'vollständig'], ['Fristfundstelle', 'markiert']],
    next_action: 'Fristfundstelle prüfen und Vorgang fachlich freigeben',
    baseline_seconds: 480,
    review_seconds: 110,
    avoided_followups: 1,
    timeline: ['Dokument erkannt', 'Fristkandidat extrahiert', 'Fundstelle markiert', 'Zur anwaltlichen Prüfung bereit']
  },
  {
    id: 'TR-GOLD-005',
    title: 'Namensschreibweise weicht ab',
    client_label: 'Võ E. · synthetisch',
    category: 'Identität',
    state: 'REVIEW',
    urgency: 'NORMAL',
    vn_original: 'Tên trên hộ chiếu của tôi có dấu tiếng Việt, nhưng trong hợp đồng tên được viết không dấu.',
    de_translation: 'Mein Name im Reisepass enthält vietnamesische Zeichen, im Vertrag wurde er ohne diakritische Zeichen geschrieben.',
    summary: 'Name weicht zwischen Pass und Vertrag ab. Kein automatisches Zusammenführen ohne Bestätigung.',
    open_points: ['Schreibweise aus Pass vs. Vertrag bestätigen'],
    documents: [['Reisepass', 'Võ …'], ['Vertrag', 'Vo …']],
    next_action: 'Originalquellen vergleichen und Identität manuell bestätigen',
    baseline_seconds: 420,
    review_seconds: 120,
    avoided_followups: 0,
    timeline: ['Identitätsfelder extrahiert', 'Schreibweisen verglichen', 'Abweichung erkannt', 'Auto-Merge blockiert']
  },
  {
    id: 'TR-GOLD-006',
    title: 'Vollständiger Erstantrag',
    client_label: 'Đặng F. · synthetisch',
    category: 'Mandantenaufnahme',
    state: 'READY',
    urgency: 'NORMAL',
    vn_original: 'Tôi đã tải lên tất cả giấy tờ theo danh sách và ký giấy ủy quyền.',
    de_translation: 'Ich habe alle Unterlagen aus der Liste hochgeladen und die Vollmacht unterschrieben.',
    summary: 'Alle erwarteten Dokumente vorhanden, lesbar und formal vollständig.',
    open_points: [],
    documents: [['Identität', 'vollständig'], ['Vollmacht', 'unterschrieben'], ['Hauptdokument', 'vollständig'], ['Nachweis', 'vollständig']],
    next_action: 'Vorgang zur fachlichen Freigabe öffnen',
    baseline_seconds: 540,
    review_seconds: 80,
    avoided_followups: 2,
    timeline: ['Checkliste vollständig', 'Uploads clean', 'Formalien geprüft', 'Keine offenen Punkte', 'Zur Freigabe bereit']
  },
  {
    id: 'TR-GOLD-007',
    title: 'Foto nicht lesbar',
    client_label: 'Bùi G. · synthetisch',
    category: 'Dokumentqualität',
    state: 'INCOMPLETE',
    urgency: 'NORMAL',
    vn_original: 'Tôi đã chụp giấy tờ bằng điện thoại nhưng ảnh hơi tối.',
    de_translation: 'Ich habe das Dokument mit dem Handy fotografiert, das Bild ist aber etwas dunkel.',
    summary: 'Relevante Felder sind nicht zuverlässig lesbar. Keine Extraktion als Tatsache übernehmen.',
    open_points: ['Dokument erneut lesbar hochladen'],
    documents: [['Bescheid-Foto', 'nicht zuverlässig lesbar']],
    next_action: 'Lesbaren Scan oder neues Foto anfordern',
    baseline_seconds: 300,
    review_seconds: 55,
    avoided_followups: 1,
    timeline: ['Bild empfangen', 'Lesbarkeit unzureichend', 'Extraktion blockiert', 'Neu-Upload vorbereitet']
  },
  {
    id: 'TR-GOLD-008',
    title: 'Falsches Dokument hochgeladen',
    client_label: 'Hồ H. · synthetisch',
    category: 'Dokumentation',
    state: 'INCOMPLETE',
    urgency: 'NORMAL',
    vn_original: 'Tôi nghĩ đây là giấy tờ mà văn phòng cần.',
    de_translation: 'Ich glaube, das ist das Dokument, das die Kanzlei benötigt.',
    summary: 'Upload passt nicht zum angeforderten Dokument-Slot. Keine automatische Umklassifizierung.',
    open_points: ['Richtiges Dokument nachfordern'],
    documents: [['Angefordert: Meldebescheinigung', 'fehlt'], ['Hochgeladen: Kontoauszug', 'falscher Slot']],
    next_action: 'Richtiges Dokument eindeutig benennen und anfordern',
    baseline_seconds: 360,
    review_seconds: 65,
    avoided_followups: 1,
    timeline: ['Upload empfangen', 'Dokumenttyp erkannt', 'Slot-Mismatch erkannt', 'Promotion in falschen Slot blockiert']
  },
  {
    id: 'TR-GOLD-009',
    title: 'Doppelte Unterlagen mit neuer Version',
    client_label: 'Ngô I. · synthetisch',
    category: 'Versionierung',
    state: 'REVIEW',
    urgency: 'NORMAL',
    vn_original: 'Tôi gửi lại hợp đồng vì trang cuối đã được sửa.',
    de_translation: 'Ich sende den Vertrag erneut, weil die letzte Seite korrigiert wurde.',
    summary: 'Neue Version vorhanden. Alte Version bleibt als Quelle erhalten; aktuelle Fassung muss gewählt werden.',
    open_points: ['Aktuelle Vertragsversion bestätigen'],
    documents: [['Vertrag v1', 'älter'], ['Vertrag v2', 'neu hochgeladen']],
    next_action: 'Versionen vergleichen und v2 als aktuelle Fassung markieren',
    baseline_seconds: 420,
    review_seconds: 105,
    avoided_followups: 0,
    timeline: ['Duplikat erkannt', 'Hashes unterscheiden sich', 'Versionen nebeneinander', 'Manuelle Aktualitätsentscheidung erforderlich']
  },
  {
    id: 'TR-GOLD-010',
    title: 'Unklare Freitextangabe',
    client_label: 'Đỗ J. · synthetisch',
    category: 'Rückfrage',
    state: 'INCOMPLETE',
    urgency: 'NORMAL',
    vn_original: 'Khoảng đầu tháng tôi đã nói chuyện với họ, nhưng tôi không nhớ chính xác ngày nào.',
    de_translation: 'Anfang des Monats habe ich mit ihnen gesprochen, aber ich weiß das genaue Datum nicht mehr.',
    summary: 'Zeitangabe ist bewusst ungenau. TrustReady darf daraus kein exaktes Datum erfinden.',
    open_points: ['Falls rechtlich relevant: genaues oder bestmöglich eingegrenztes Datum erfragen'],
    documents: [],
    next_action: 'Gezielte vietnamesische Rückfrage vorbereiten',
    baseline_seconds: 300,
    review_seconds: 60,
    avoided_followups: 1,
    timeline: ['Freitext strukturiert', 'Unsicherheitsmarker erkannt', 'Kein exaktes Datum erzeugt', 'Rückfrage empfohlen']
  },
  {
    id: 'TR-GOLD-011',
    title: 'Sensibler Sonderfall → Eskalation',
    client_label: 'Mai K. · synthetisch',
    category: 'Eskalation',
    state: 'REVIEW',
    urgency: 'HIGH',
    vn_original: 'Tôi cần tư vấn gấp vì tình huống của tôi phức tạp và có nhiều tài liệu nhạy cảm.',
    de_translation: 'Ich brauche dringend Beratung, weil meine Situation komplex ist und viele sensible Unterlagen enthält.',
    summary: 'Kein Standard-Intake. System stoppt Automatisierung und eskaliert zur anwaltlichen Sichtung.',
    open_points: ['Bao muss Scope und nächsten Schritt festlegen'],
    documents: [['Sensible Unterlagen', 'nicht automatisch weiterverarbeiten']],
    next_action: 'Direkt an Bao zur manuellen Sichtung eskalieren',
    baseline_seconds: 300,
    review_seconds: 45,
    avoided_followups: 0,
    timeline: ['Sensitivitätsregel ausgelöst', 'Standard-Automation gestoppt', 'Externer Egress blockiert', 'Bao-Review erforderlich']
  },
  {
    id: 'TR-GOLD-012',
    title: 'Bereit zur Freigabe mit Entwurf',
    client_label: 'Vũ L. · synthetisch',
    category: 'Freigabe',
    state: 'READY',
    urgency: 'NORMAL',
    vn_original: 'Tôi đã bổ sung tất cả giấy tờ còn thiếu. Xin vui lòng xác nhận văn phòng đã nhận đủ.',
    de_translation: 'Ich habe alle fehlenden Unterlagen ergänzt. Bitte bestätigen Sie, dass die Kanzlei nun alles erhalten hat.',
    summary: 'Vorgang vollständig. Antwortentwurf kann fachlich geprüft werden; öffentlicher Rehearsal sendet nichts.',
    open_points: [],
    documents: [['Checkliste', 'vollständig'], ['Rückläufer', 'alle ergänzt']],
    next_action: 'Entwurf prüfen und fachlich freigeben',
    baseline_seconds: 480,
    review_seconds: 75,
    avoided_followups: 2,
    timeline: ['Fehlende Unterlagen ergänzt', 'Vollständigkeit erneut geprüft', 'Entwurf vorbereitet', 'Zur Freigabe bereit']
  }
])

export const GOLDEN_CASE_STATES = Object.freeze(['INCOMPLETE', 'REVIEW', 'READY', 'DONE'])
