import test from 'node:test'
import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import {createKeyTrustStore,issueIdentityAssertion,signEnvelope,verifyEnvelope} from './legal-key-identity.mjs'
import {inspectPayload} from './legal-dlp.mjs'
import {authorizeLegalEgress,executeApprovedAction,issueActionApproval,signProviderPassport,validateActionPayload} from './legal-runtime-fortress.mjs'

const NOW=new Date('2026-09-02T12:00:00Z'),H=`sha256:${'a'.repeat(64)}`,H2=`sha256:${'b'.repeat(64)}`
const idp=crypto.generateKeyPairSync('ed25519'),reviewer=crypto.generateKeyPairSync('ed25519'),approver=crypto.generateKeyPairSync('ed25519'),network=crypto.generateKeyPairSync('ed25519'),egressKey=crypto.generateKeyPairSync('ed25519')
const keyStore=()=>createKeyTrustStore([{key_id:'idp-1',purpose:'identity',public_key:idp.publicKey,not_after:'2027-01-01T00:00:00Z'},{key_id:'review-1',purpose:'provider_review',public_key:reviewer.publicKey,not_after:'2027-01-01T00:00:00Z'},{key_id:'approval-1',purpose:'action_approval',public_key:approver.publicKey,not_after:'2027-01-01T00:00:00Z'},{key_id:'network-1',purpose:'network_attestation',public_key:network.publicKey,not_after:'2027-01-01T00:00:00Z'},{key_id:'egress-1',purpose:'egress_enforcement',public_key:egressKey.publicKey,not_after:'2027-01-01T00:00:00Z'}])
function identity(overrides={}){return issueIdentityAssertion({subject:'bao',tenant_id:'tenant-a',session_id:'s1',roles:['lawyer'],mfa:true,matter_permissions:[{matter_id:'m1',operations:['egress','approve_action','execute_action']}],auth_time:'2026-09-02T11:58:00Z',expires_at:'2026-09-02T12:20:00Z',private_key:idp.privateKey,key_id:'idp-1',now:NOW,...overrides})}
function passport(overrides={}){const body={policy_version:'legal-v2',provider_id:'eu-ai',status:'approved',valid_until:'2026-12-31T00:00:00Z',training_on_customer_data:false,avv_status:'approved',brao_43e_status:'approved',subprocessor_status:'approved',third_country:false,use_cases:{summarise_mail:{allowed_zones:['MANDATE'],regions:['eu-central'],max_retention_minutes:0,allowed_fields:['subject_hash','body_excerpt'],allowed_sensitive_keys:[],max_payload_bytes:4096,endpoints:{'eu-central':['https://eu-ai.example']}}},...overrides};return signProviderPassport({body,private_key:reviewer.privateKey,key_id:'review-1'})}
function request(overrides={}){return{actor_session_id:'s1',tenant_id:'tenant-a',matter_id:'m1',provider_id:'eu-ai',zone:'MANDATE',use_case:'summarise_mail',purpose:'triage',policy_version:'legal-v2',region:'eu-central',endpoint:'https://eu-ai.example/v1',retention_minutes:0,payload:{subject_hash:H,body_excerpt:'Pseudonymised short excerpt'},...overrides}}
const state={external_ai_enabled:true,outbound_actions_enabled:true,policy_version:'legal-v2',release:'r2',disabled_tenants:[],disabled_providers:[]}
const egress=(overrides={})=>signEnvelope({body:{schema:'trustready-egress-enforcement-v1',tenant_id:'tenant-a',policy_version:'legal-v2',deny_by_default:true,only_gateway:true,release:'r2',observed_at:'2026-09-02T12:00:00Z',expires_at:'2026-09-02T12:04:00Z',...overrides},private_key:egressKey.privateKey,key_id:'egress-1',purpose:'egress_enforcement'})
const probe=({endpoint,hostname,region})=>signEnvelope({body:{schema:'trustready-network-attestation-v1',endpoint,hostname,region,tls:true,certificate_valid:true,redirected:false,peer_fingerprint:H,observed_at:'2026-09-02T12:00:00Z',expires_at:'2026-09-02T12:00:30Z'},private_key:network.privateKey,key_id:'network-1',purpose:'network_attestation'})
function allow(overrides={}){return authorizeLegalEgress({identity_assertion:identity(),request:request(),provider_passport:passport(),key_store:keyStore(),runtime_state:state,network_probe:probe,egress_enforcement_attestation:egress(),now:NOW,...overrides})}

test('full non-production egress requires signed identity, matter ABAC, provider approval, release-bound egress proof and network proof',()=>{const r=allow();assert.equal(r.allowed,true);assert.equal(r.actor_id,'bao');assert.equal(r.network_attestor,'network-1');assert.equal(r.release,'r2')})
test('request tenant session and matter claims cannot self-authorise',()=>{for(const[change,code]of[[{tenant_id:'tenant-b'},'EGRESS_ENFORCEMENT_DENIED'],[{actor_session_id:'attacker'},'SESSION_MISMATCH'],[{matter_id:'m2'},'MATTER_DENIED']])assert.equal(authorizeLegalEgress({identity_assertion:identity(),request:request(change),provider_passport:passport(),key_store:keyStore(),runtime_state:state,network_probe:probe,egress_enforcement_attestation:egress(),now:NOW}).code,code)})
test('mandate requires MFA and Zone 4 never leaves externally',()=>{assert.equal(allow({identity_assertion:identity({mfa:false})}).code,'MATTER_DENIED');assert.equal(allow({request:request({zone:'RESTRICTED'})}).code,'RESTRICTED_EXTERNAL_DENIED')})
test('DLP detects nested unicode base64url identifiers and parser abuse',()=>{const unpadded=Buffer.from('alice@example.com').toString('base64url'),urlSafe=Buffer.from('Bearer supersecrettoken123').toString('base64url');for(const payload of[{body_excerpt:{x:'person@example.com'}},{body_excerpt:'p\u200Berson@example.com'},{body_excerpt:Buffer.from('Bearer supersecrettoken123').toString('base64')},{body_excerpt:unpadded},{body_excerpt:urlSafe},{body_excerpt:{client_name:'Alice'}}])assert.equal(inspectPayload(payload).safe,false);let deep='x';for(let i=0;i<12;i++)deep={a:deep};assert.ok(inspectPayload(deep).findings.some(f=>f.type==='depth_limit'))})
test('prototype property zone names cannot bypass mandate controls',()=>{assert.equal(allow({request:request({zone:'toString'})}).code,'INVALID_REQUEST')})
test('network egress blocks wrong host http redirect unknown redirect and forged signer',()=>{const redirected=({endpoint,hostname,region})=>signEnvelope({body:{schema:'trustready-network-attestation-v1',endpoint,hostname,region,tls:true,certificate_valid:true,redirected:true,observed_at:NOW.toISOString(),expires_at:'2026-09-02T12:00:30Z'},private_key:network.privateKey,key_id:'network-1',purpose:'network_attestation'}),unknown=({endpoint,hostname,region})=>signEnvelope({body:{schema:'trustready-network-attestation-v1',endpoint,hostname,region,tls:true,certificate_valid:true,observed_at:NOW.toISOString(),expires_at:'2026-09-02T12:00:30Z'},private_key:network.privateKey,key_id:'network-1',purpose:'network_attestation'}),forged=({endpoint,hostname,region})=>signEnvelope({body:{schema:'trustready-network-attestation-v1',endpoint,hostname,region,tls:true,certificate_valid:true,redirected:false,observed_at:NOW.toISOString(),expires_at:'2026-09-02T12:00:30Z'},private_key:approver.privateKey,key_id:'approval-1',purpose:'network_attestation'});for(const[req,np]of[[request({endpoint:'https://evil.example'}),probe],[request({endpoint:'http://eu-ai.example'}),probe],[request(),undefined],[request(),redirected],[request(),unknown],[request(),forged]])assert.equal(authorizeLegalEgress({identity_assertion:identity(),request:req,provider_passport:passport(),key_store:keyStore(),runtime_state:state,network_probe:np,egress_enforcement_attestation:egress(),now:NOW}).code,'NETWORK_DENIED')})
test('stale provider passport and stale release proof are revoked',()=>{assert.equal(allow({provider_passport:passport({policy_version:'legal-v1'})}).code,'PROVIDER_DENIED');assert.equal(allow({egress_enforcement_attestation:egress({release:'r1'})}).code,'EGRESS_ENFORCEMENT_DENIED')})
test('key revocation and kill switches fail closed immediately',()=>{const ks=keyStore();ks.revoke('review-1');assert.equal(allow({key_store:ks}).code,'PROVIDER_DENIED');for(const runtime_state of[{...state,external_ai_enabled:false},{...state,disabled_tenants:['tenant-a']},{...state,disabled_providers:['eu-ai']}])assert.equal(allow({runtime_state}).code,'KILL_SWITCH')})
test('typed actions reject surprise fields raw recipients and invalid hashes',()=>{const good={message_id:'msg1',recipient_refs:['party-1'],subject_hash:H,body_hash:H2,resource_version:'v1'};assert.equal(validateActionPayload('send_email',good).valid,true);assert.equal(validateActionPayload('send_email',{...good,bcc:'attacker'}).valid,false);assert.equal(validateActionPayload('send_email',{...good,recipient_refs:['evil@example.com']}).valid,false);assert.equal(validateActionPayload('send_email',{...good,body_hash:'not-a-hash'}).valid,false)})
test('action approval remains exact-payload signed and needs recent step-up',()=>{const ks=keyStore(),payload={task_id:'t1',resource_version:'v7'},cap=issueActionApproval({identity_assertion:identity(),key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'complete_task',payload,policy_version:'legal-v2',expires_at:'2026-09-02T12:03:00Z',private_key:approver.privateKey,key_id:'approval-1',now:NOW});const v=verifyEnvelope({envelope:cap,key_store:ks,purpose:'action_approval',now:NOW});assert.equal(v.valid,true);assert.equal(v.body.payload_hash,`sha256:${crypto.createHash('sha256').update(JSON.stringify({resource_version:'v7',task_id:'t1'})).digest('hex')}`);assert.throws(()=>issueActionApproval({identity_assertion:identity({auth_time:'2026-09-02T11:30:00Z'}),key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'complete_task',payload,policy_version:'legal-v2',expires_at:'2026-09-02T12:03:00Z',private_key:approver.privateKey,key_id:'approval-1',now:NOW}),/step-up/)})
test('shadow and production action execution cannot reach caller replay stores or handlers',async()=>{let claims=0,executions=0;const fake={durable:true,atomic:true,claim:async()=>{claims++;return true}},handler=async()=>{executions++;return{ok:true}},base={tenant_id:'tenant-a',policy_version:'legal-v2',runtime_state:state,replay_store:fake,action_handler:handler};assert.equal((await executeApprovedAction({...base,deployment_mode:'shadow'})).code,'SHADOW_LOCK');assert.equal((await executeApprovedAction({...base,deployment_mode:'production'})).code,'PRODUCTION_ACTIONS_DISABLED');assert.equal(claims,0);assert.equal(executions,0)})
test('unknown action deployment mode fails closed before callbacks',async()=>{let touched=false;const r=await executeApprovedAction({tenant_id:'tenant-a',policy_version:'legal-v2',runtime_state:state,deployment_mode:'prodution',replay_store:{claim:async()=>{touched=true;return true}},action_handler:async()=>{touched=true}});assert.equal(r.code,'DEPLOYMENT_MODE_DENIED');assert.equal(touched,false)})
test('egress release gate needs fresh separately signed infrastructure proof',()=>{const missing=allow({egress_enforcement_attestation:undefined});assert.equal(missing.code,'EGRESS_ENFORCEMENT_DENIED');const forged=signEnvelope({body:{schema:'trustready-egress-enforcement-v1',tenant_id:'tenant-a',policy_version:'legal-v2',deny_by_default:true,only_gateway:true,release:'r2',observed_at:NOW.toISOString(),expires_at:'2026-09-02T12:04:00Z'},private_key:approver.privateKey,key_id:'approval-1',purpose:'egress_enforcement'});assert.equal(allow({egress_enforcement_attestation:forged}).code,'EGRESS_ENFORCEMENT_DENIED')})
