import test from 'node:test'
import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import {createKeyTrustStore} from './legal-key-identity.mjs'
import {appendEvidenceEvent,buildEvidenceManifest,signEvidenceCheckpoint,signEvidenceManifest,verifyEvidenceBundle,verifyEvidenceChain,verifyEvidenceCheckpoint} from './legal-evidence.mjs'
const kp=crypto.generateKeyPairSync('ed25519'),ks=createKeyTrustStore([{key_id:'evidence-1',purpose:'evidence_manifest',public_key:kp.publicKey},{key_id:'checkpoint-1',purpose:'evidence_checkpoint',public_key:kp.publicKey}])
test('evidence chain detects mutation deletion and reorder',()=>{const e1=appendEvidenceEvent({sequence:1,event:{event_type:'egress.denied',occurred_at:'2026-09-02T12:00:00Z',tenant_id:'t',metadata:{code:'DLP_DENIED'}}}),e2=appendEvidenceEvent({previous_hash:e1.event_hash,sequence:2,event:{event_type:'approval.consumed',occurred_at:'2026-09-02T12:01:00Z',tenant_id:'t',metadata:{capability_id:'c1'}}});assert.equal(verifyEvidenceChain([e1,e2]).valid,true);assert.equal(verifyEvidenceChain([e2,e1]).valid,false);assert.equal(verifyEvidenceChain([{...e1,actor_id:'x'},e2]).valid,false)})
test('evidence metadata rejects raw secrets and identifiers',()=>{for(const metadata of[{prompt:'x'},{note:'person@example.com'},{token:'abc'},{safe:'-----BEGIN PRIVATE KEY-----'}])assert.throws(()=>appendEvidenceEvent({sequence:1,event:{event_type:'x',occurred_at:'2026-09-02T12:00:00Z',tenant_id:'t',metadata}}))})
test('signed checkpoint cannot be rewritten',()=>{const cp=signEvidenceCheckpoint({body:{schema:'trustready-evidence-checkpoint-v2',tenant_id:'t',head_hash:`sha256:${'a'.repeat(64)}`,sequence:2,generated_at:'2026-09-02T12:02:00Z'},private_key:kp.privateKey,key_id:'checkpoint-1'});assert.equal(verifyEvidenceCheckpoint({checkpoint:cp,key_store:ks}).valid,true);const changed=structuredClone(cp);changed.body.sequence=1;assert.equal(verifyEvidenceCheckpoint({checkpoint:changed,key_store:ks}).valid,false)})
test('evidence bundle recomputes actual artifact bytes and detects replacement/add/remove',()=>{const artifacts={'controls.json':{ok:true},'runtime.txt':'green'},manifest=buildEvidenceManifest({tenant:'t',release:'r2',policy_version:'legal-v2',artifacts,generated_at:'2026-09-02T12:03:00Z'}),signed=signEvidenceManifest({manifest,private_key:kp.privateKey,key_id:'evidence-1'});assert.equal(verifyEvidenceBundle({signed_manifest:signed,key_store:ks,artifacts}).valid,true);assert.equal(verifyEvidenceBundle({signed_manifest:signed,key_store:ks,artifacts:{...artifacts,'runtime.txt':'tampered'}}).valid,false);assert.equal(verifyEvidenceBundle({signed_manifest:signed,key_store:ks,artifacts:{...artifacts,'extra.txt':'x'}}).valid,false);assert.equal(verifyEvidenceBundle({signed_manifest:signed,key_store:ks,artifacts:{'controls.json':artifacts['controls.json']}}).valid,false)})
