import test from 'node:test'
import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import {createKeyTrustStore,createRootedKeyTrustStore,issueIdentityAssertion,issueMatterAuthorization,publicKeyFingerprint,signEnvelope,signKeyring} from './legal-key-identity.mjs'
import {inspectPayload} from './legal-dlp.mjs'
import {buildProposalOnlyModelRequest,validateAgentProposal} from './legal-content-guard.mjs'
import {authorizeLegalEgress,executeApprovedAction,issueActionApproval,signProviderPassport} from './legal-runtime-fortress.mjs'

const NOW=new Date('2026-09-02T12:00:00Z'),H=`sha256:${'a'.repeat(64)}`,DLP_CFG=`sha256:${'d'.repeat(64)}`
const root=crypto.generateKeyPairSync('ed25519'),idp=crypto.generateKeyPairSync('ed25519'),matter=crypto.generateKeyPairSync('ed25519'),reviewer=crypto.generateKeyPairSync('ed25519'),approval=crypto.generateKeyPairSync('ed25519'),network=crypto.generateKeyPairSync('ed25519'),egress=crypto.generateKeyPairSync('ed25519'),dlp=crypto.generateKeyPairSync('ed25519')
const keys=[['idp-1','identity',idp],['matter-1','matter_authorization',matter],['review-1','provider_review',reviewer],['approval-1','action_approval',approval],['network-1','network_attestation',network],['egress-1','egress_enforcement',egress],['dlp-1','dlp_attestation',dlp]].map(([key_id,purpose,k])=>({key_id,purpose,public_key:k.publicKey,not_after:'2027-01-01T00:00:00Z'}))
const signedKeyring=signKeyring({keys,version:'legal-keys-v1',valid_until:'2026-12-31T00:00:00Z',private_key:root.privateKey,key_id:'offline-root-1'})
const rooted=()=>createRootedKeyTrustStore({signed_keyring:signedKeyring,pinned_root_public_key:root.publicKey,expected_root_fingerprint:publicKeyFingerprint(root.publicKey),now:NOW})
const unrooted=()=>createKeyTrustStore(keys)
function identity(){return issueIdentityAssertion({subject:'bao',tenant_id:'tenant-a',session_id:'s1',roles:['lawyer'],mfa:true,matter_permissions:[{matter_id:'m1',operations:['egress','approve_action','execute_action']}],auth_time:'2026-09-02T11:58:00Z',expires_at:'2026-09-02T12:20:00Z',private_key:idp.privateKey,key_id:'idp-1',now:NOW})}
function matterAuth(operations=['egress'],resource_version='matter-v4',expires_at='2026-09-02T12:00:45Z'){return issueMatterAuthorization({subject:'bao',tenant_id:'tenant-a',session_id:'s1',matter_id:'m1',operations,resource_version,expires_at,private_key:matter.privateKey,key_id:'matter-1',now:NOW})}
function provider(){return signProviderPassport({body:{policy_version:'legal-v3',provider_id:'eu-ai',status:'approved',valid_until:'2026-12-31T00:00:00Z',training_on_customer_data:false,avv_status:'approved',brao_43e_status:'approved',subprocessor_status:'approved',third_country:false,use_cases:{summarise_mail:{allowed_zones:['MANDATE'],regions:['eu-central'],max_retention_minutes:0,allowed_fields:['subject_hash','body_excerpt'],allowed_sensitive_keys:[],max_payload_bytes:4096,endpoints:{'eu-central':['https://eu-ai.example']}}}},private_key:reviewer.privateKey,key_id:'review-1'})}
const payload={subject_hash:H,body_excerpt:'Pseudonymised short excerpt'}
function request(overrides={}){return{actor_session_id:'s1',tenant_id:'tenant-a',matter_id:'m1',matter_version:'matter-v4',provider_id:'eu-ai',zone:'MANDATE',use_case:'summarise_mail',purpose:'triage',policy_version:'legal-v3',region:'eu-central',endpoint:'https://eu-ai.example/v1',retention_minutes:0,payload,...overrides}}
const state={production:true,external_ai_enabled:true,outbound_actions_enabled:true,policy_version:'legal-v3',release:'r3',dlp_config_fingerprint:DLP_CFG,disabled_tenants:[],disabled_providers:[]}
const egressProof=(overrides={})=>signEnvelope({body:{schema:'trustready-egress-enforcement-v1',tenant_id:'tenant-a',policy_version:'legal-v3',deny_by_default:true,only_gateway:true,release:'r3',observed_at:NOW.toISOString(),expires_at:'2026-09-02T12:04:00Z',...overrides},private_key:egress.privateKey,key_id:'egress-1',purpose:'egress_enforcement'})
const probe=({endpoint,hostname,region})=>signEnvelope({body:{schema:'trustready-network-attestation-v1',endpoint,hostname,region,tls:true,certificate_valid:true,redirected:false,peer_fingerprint:H,observed_at:NOW.toISOString(),expires_at:'2026-09-02T12:00:30Z'},private_key:network.privateKey,key_id:'network-1',purpose:'network_attestation'})
function dlpProof(inputPayload=payload,overrides={}){const fingerprint=inspectPayload(inputPayload).fingerprint;return signEnvelope({body:{schema:'trustready-dlp-attestation-v2',safe:true,tenant_id:'tenant-a',matter_id:'m1',payload_fingerprint:fingerprint,policy_version:'legal-v3',detected_categories:[],findings_count:0,scanner_id:'local-pii-guard',scanner_version:'2.0.0',scanner_config_fingerprint:DLP_CFG,observed_at:NOW.toISOString(),expires_at:'2026-09-02T12:00:45Z',...overrides},private_key:dlp.privateKey,key_id:'dlp-1',purpose:'dlp_attestation'})}
function prodEgress(overrides={}){return authorizeLegalEgress({identity_assertion:identity(),matter_authorization:matterAuth(),dlp_attestation:dlpProof(),request:request(),provider_passport:provider(),key_store:rooted(),runtime_state:state,network_probe:probe,egress_enforcement_attestation:egressProof(),now:NOW,...overrides})}

test('production refuses caller-assembled trust roots and accepts offline-root-signed keyring',()=>{assert.equal(prodEgress({key_store:unrooted()}).code,'ROOT_TRUST_REQUIRED');const allowed=prodEgress();assert.equal(allowed.allowed,true);assert.equal(allowed.matter_auth_signer,'matter-1');assert.equal(allowed.dlp_signer,'dlp-1')})
test('root fingerprint mismatch and keyring tampering fail closed',()=>{assert.throws(()=>createRootedKeyTrustStore({signed_keyring:signedKeyring,pinned_root_public_key:root.publicKey,expected_root_fingerprint:`sha256:${'0'.repeat(64)}`,now:NOW}),/fingerprint/);const tampered=structuredClone(signedKeyring);tampered.body.version='attacker';assert.throws(()=>createRootedKeyTrustStore({signed_keyring:tampered,pinned_root_public_key:root.publicKey,expected_root_fingerprint:publicKeyFingerprint(root.publicKey),now:NOW}),/signature/)})
test('production needs fresh matter authorization bound to current matter version',()=>{assert.equal(prodEgress({matter_authorization:undefined}).code,'FRESH_MATTER_AUTH_REQUIRED');assert.equal(prodEgress({matter_authorization:matterAuth(['egress'],'matter-v3')}).code,'FRESH_MATTER_AUTH_REQUIRED');const expired=matterAuth(['egress'],'matter-v4','2026-09-02T12:00:20Z');assert.equal(prodEgress({matter_authorization:expired,now:new Date('2026-09-02T12:00:30Z')}).code,'FRESH_MATTER_AUTH_REQUIRED')})
test('production needs independent DLP attestation for exact payload policy and scanner config',()=>{assert.equal(prodEgress({dlp_attestation:undefined}).code,'DLP_ATTESTATION_REQUIRED');assert.equal(prodEgress({dlp_attestation:dlpProof({subject_hash:H,body_excerpt:'different'})}).code,'DLP_ATTESTATION_REQUIRED');assert.equal(prodEgress({dlp_attestation:dlpProof(payload,{policy_version:'old'})}).code,'DLP_ATTESTATION_REQUIRED');assert.equal(prodEgress({dlp_attestation:dlpProof(payload,{scanner_config_fingerprint:`sha256:${'e'.repeat(64)}`})}).code,'DLP_ATTESTATION_REQUIRED')})
test('production egress proof is bound to exact deployment release',()=>{assert.equal(prodEgress({egress_enforcement_attestation:egressProof({release:'r2'})}).code,'EGRESS_ENFORCEMENT_DENIED');assert.equal(prodEgress({runtime_state:{...state,release:null}}).code,'RELEASE_REQUIRED')})
test('DLP rejects cyclic payloads without recursing during canonical hash',()=>{const cyclic={body_excerpt:'safe'};cyclic.self=cyclic;const inspected=inspectPayload(cyclic);assert.equal(inspected.safe,false);assert.equal(inspected.fingerprint,null);assert.ok(inspected.findings.some(f=>f.type==='cycle_detected'))})
test('model boundary is proposal-only with no tools network code or persistent memory',()=>{const decision=prodEgress();const req=buildProposalOnlyModelRequest({egress_decision:decision,payload,use_case:'summarise_mail'});assert.deepEqual(req.security.tools,[]);assert.equal(req.security.network_access,false);assert.equal(req.security.code_execution,false);assert.equal(req.security.persistent_memory,false);assert.equal(req.security.external_actions,false);assert.equal(validateAgentProposal({type:'summary',text:'Short neutral summary',source_refs:['doc-1']}).valid,true);assert.equal(validateAgentProposal({type:'summary',text:'x',tool:'send_email',source_refs:[]}).valid,false);assert.equal(validateAgentProposal({type:'draft_reply',text:'Draft only',recipient:'victim',source_refs:[]}).valid,false)})
test('rooted production approval may be prepared but production execution remains physically disabled',async()=>{const ks=rooted(),actionPayload={task_id:'t1',resource_version:'v7'},approveAuth=matterAuth(['approve_action'],'v7');assert.throws(()=>issueActionApproval({identity_assertion:identity(),matter_authorization:approveAuth,key_store:unrooted(),tenant_id:'tenant-a',matter_id:'m1',action:'complete_task',payload:actionPayload,policy_version:'legal-v3',expires_at:'2026-09-02T12:03:00Z',private_key:approval.privateKey,key_id:'approval-1',production:true,now:NOW}),/root-pinned/);issueActionApproval({identity_assertion:identity(),matter_authorization:approveAuth,key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'complete_task',payload:actionPayload,policy_version:'legal-v3',expires_at:'2026-09-02T12:03:00Z',private_key:approval.privateKey,key_id:'approval-1',production:true,now:NOW});let claims=0,executions=0;const result=await executeApprovedAction({tenant_id:'tenant-a',policy_version:'legal-v3',runtime_state:state,deployment_mode:'production',replay_store:{durable:true,atomic:true,claim:async()=>{claims++;return true}},action_handler:async()=>{executions++;return{ok:true}},now:NOW});assert.equal(result.code,'PRODUCTION_ACTIONS_DISABLED');assert.equal(claims,0);assert.equal(executions,0);const typo=await executeApprovedAction({tenant_id:'tenant-a',policy_version:'legal-v3',runtime_state:state,deployment_mode:'prodution'});assert.equal(typo.code,'DEPLOYMENT_MODE_DENIED')})
