import test from 'node:test'
import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import {createKeyTrustStore,issueIdentityAssertion,signEnvelope} from './legal-key-identity.mjs'
import {inspectPayload} from './legal-dlp.mjs'
import {authorizeLegalEgress,executeApprovedAction,issueActionApproval,signProviderPassport,validateActionPayload} from './legal-runtime-fortress.mjs'

const NOW=new Date('2026-09-02T12:00:00Z'),H=`sha256:${'a'.repeat(64)}`,H2=`sha256:${'b'.repeat(64)}`
const idp=crypto.generateKeyPairSync('ed25519'),reviewer=crypto.generateKeyPairSync('ed25519'),approver=crypto.generateKeyPairSync('ed25519'),network=crypto.generateKeyPairSync('ed25519'),egressKey=crypto.generateKeyPairSync('ed25519')
const keyStore=()=>createKeyTrustStore([{key_id:'idp-1',purpose:'identity',public_key:idp.publicKey,not_after:'2027-01-01T00:00:00Z'},{key_id:'review-1',purpose:'provider_review',public_key:reviewer.publicKey,not_after:'2027-01-01T00:00:00Z'},{key_id:'approval-1',purpose:'action_approval',public_key:approver.publicKey,not_after:'2027-01-01T00:00:00Z'},{key_id:'network-1',purpose:'network_attestation',public_key:network.publicKey,not_after:'2027-01-01T00:00:00Z'},{key_id:'egress-1',purpose:'egress_enforcement',public_key:egressKey.publicKey,not_after:'2027-01-01T00:00:00Z'}])
function identity(overrides={}){return issueIdentityAssertion({subject:'bao',tenant_id:'tenant-a',session_id:'s1',roles:['lawyer'],mfa:true,matter_permissions:[{matter_id:'m1',operations:['egress','approve_action','execute_action']}],auth_time:'2026-09-02T11:58:00Z',expires_at:'2026-09-02T12:20:00Z',private_key:idp.privateKey,key_id:'idp-1',now:NOW,...overrides})}
function passport(overrides={}){const body={policy_version:'legal-v2',provider_id:'eu-ai',status:'approved',valid_until:'2026-12-31T00:00:00Z',training_on_customer_data:false,avv_status:'approved',brao_43e_status:'approved',subprocessor_status:'approved',third_country:false,use_cases:{summarise_mail:{allowed_zones:['MANDATE'],regions:['eu-central'],max_retention_minutes:0,allowed_fields:['subject_hash','body_excerpt'],allowed_sensitive_keys:[],max_payload_bytes:4096,endpoints:{'eu-central':['https://eu-ai.example']}}},...overrides};return signProviderPassport({body,private_key:reviewer.privateKey,key_id:'review-1'})}
function request(overrides={}){return{actor_session_id:'s1',tenant_id:'tenant-a',matter_id:'m1',provider_id:'eu-ai',zone:'MANDATE',use_case:'summarise_mail',purpose:'triage',policy_version:'legal-v2',region:'eu-central',endpoint:'https://eu-ai.example/v1',retention_minutes:0,payload:{subject_hash:H,body_excerpt:'Pseudonymised short excerpt'},...overrides}}
const state={external_ai_enabled:true,outbound_actions_enabled:true,policy_version:'legal-v2',disabled_tenants:[],disabled_providers:[]}
const egress=()=>signEnvelope({body:{schema:'trustready-egress-enforcement-v1',tenant_id:'tenant-a',policy_version:'legal-v2',deny_by_default:true,only_gateway:true,release:'r2',observed_at:'2026-09-02T12:00:00Z',expires_at:'2026-09-02T12:04:00Z'},private_key:egressKey.privateKey,key_id:'egress-1',purpose:'egress_enforcement'})
const probe=({endpoint,hostname,region})=>signEnvelope({body:{schema:'trustready-network-attestation-v1',endpoint,hostname,region,tls:true,certificate_valid:true,redirected:false,peer_fingerprint:H,observed_at:'2026-09-02T12:00:00Z',expires_at:'2026-09-02T12:00:30Z'},private_key:network.privateKey,key_id:'network-1',purpose:'network_attestation'})

test('full egress requires signed identity, matter ABAC, provider approval, DLP and signed network proof',()=>{const r=authorizeLegalEgress({identity_assertion:identity(),request:request(),provider_passport:passport(),key_store:keyStore(),runtime_state:state,network_probe:probe,egress_enforcement_attestation:egress(),now:NOW});assert.equal(r.allowed,true);assert.equal(r.actor_id,'bao');assert.equal(r.network_attestor,'network-1')})
test('request tenant/session/matter claims cannot self-authorise',()=>{for(const[change,code]of[[{tenant_id:'tenant-b'},'EGRESS_ENFORCEMENT_DENIED'],[{actor_session_id:'attacker'},'SESSION_MISMATCH'],[{matter_id:'m2'},'MATTER_DENIED']])assert.equal(authorizeLegalEgress({identity_assertion:identity(),request:request(change),provider_passport:passport(),key_store:keyStore(),runtime_state:state,network_probe:probe,egress_enforcement_attestation:egress(),now:NOW}).code,code)})
test('mandate requires MFA and Zone 4 never leaves externally',()=>{assert.equal(authorizeLegalEgress({identity_assertion:identity({mfa:false}),request:request(),provider_passport:passport(),key_store:keyStore(),runtime_state:state,network_probe:probe,egress_enforcement_attestation:egress(),now:NOW}).code,'MATTER_DENIED');assert.equal(authorizeLegalEgress({identity_assertion:identity(),request:request({zone:'RESTRICTED'}),provider_passport:passport(),key_store:keyStore(),runtime_state:state,network_probe:probe,egress_enforcement_attestation:egress(),now:NOW}).code,'RESTRICTED_EXTERNAL_DENIED')})
test('DLP detects nested, unicode/base64-obfuscated secrets and parser depth abuse',()=>{const unpadded=Buffer.from('alice@example.com').toString('base64url');const urlSafe=Buffer.from('Bearer supersecrettoken123').toString('base64url');for(const payload of[{body_excerpt:{x:'person@example.com'}},{body_excerpt:'p\u200Berson@example.com'},{body_excerpt:Buffer.from('Bearer supersecrettoken123').toString('base64')},{body_excerpt:unpadded},{body_excerpt:urlSafe},{body_excerpt:{client_name:'Alice'}}])assert.equal(inspectPayload(payload).safe,false);let deep='x';for(let i=0;i<12;i++)deep={a:deep};assert.ok(inspectPayload(deep).findings.some(f=>f.type==='depth_limit'))})
test('prototype property zone names cannot bypass mandate controls',()=>{const r=authorizeLegalEgress({identity_assertion:identity(),request:request({zone:'toString'}),provider_passport:passport(),key_store:keyStore(),runtime_state:state,network_probe:probe,egress_enforcement_attestation:egress(),now:NOW});assert.equal(r.code,'INVALID_REQUEST')})
test('network egress blocks wrong host, http, redirect, absent, unknown redirect or forged attestation',()=>{const redirected=({endpoint,hostname,region})=>signEnvelope({body:{schema:'trustready-network-attestation-v1',endpoint,hostname,region,tls:true,certificate_valid:true,redirected:true,observed_at:'2026-09-02T12:00:00Z',expires_at:'2026-09-02T12:00:30Z'},private_key:network.privateKey,key_id:'network-1',purpose:'network_attestation'});const unknownRedirect=({endpoint,hostname,region})=>signEnvelope({body:{schema:'trustready-network-attestation-v1',endpoint,hostname,region,tls:true,certificate_valid:true,observed_at:'2026-09-02T12:00:00Z',expires_at:'2026-09-02T12:00:30Z'},private_key:network.privateKey,key_id:'network-1',purpose:'network_attestation'});const forged=({endpoint,hostname,region})=>signEnvelope({body:{schema:'trustready-network-attestation-v1',endpoint,hostname,region,tls:true,certificate_valid:true,redirected:false,observed_at:'2026-09-02T12:00:00Z',expires_at:'2026-09-02T12:00:30Z'},private_key:approver.privateKey,key_id:'approval-1',purpose:'network_attestation'});for(const[req,np]of[[request({endpoint:'https://evil.example'}),probe],[request({endpoint:'http://eu-ai.example'}),probe],[request(),undefined],[request(),redirected],[request(),unknownRedirect],[request(),forged]])assert.equal(authorizeLegalEgress({identity_assertion:identity(),request:req,provider_passport:passport(),key_store:keyStore(),runtime_state:state,network_probe:np,egress_enforcement_attestation:egress(),now:NOW}).code,'NETWORK_DENIED')})
test('stale provider passport is revoked by active policy version',()=>{const stale=passport({policy_version:'legal-v1'});assert.equal(authorizeLegalEgress({identity_assertion:identity(),request:request(),provider_passport:stale,key_store:keyStore(),runtime_state:state,network_probe:probe,egress_enforcement_attestation:egress(),now:NOW}).code,'PROVIDER_DENIED')})
test('key revocation and kill switches fail closed immediately',()=>{const ks=keyStore();ks.revoke('review-1');assert.equal(authorizeLegalEgress({identity_assertion:identity(),request:request(),provider_passport:passport(),key_store:ks,runtime_state:state,network_probe:probe,egress_enforcement_attestation:egress(),now:NOW}).code,'PROVIDER_DENIED');for(const runtime_state of[{...state,external_ai_enabled:false},{...state,disabled_tenants:['tenant-a']},{...state,disabled_providers:['eu-ai']}])assert.equal(authorizeLegalEgress({identity_assertion:identity(),request:request(),provider_passport:passport(),key_store:keyStore(),runtime_state,network_probe:probe,egress_enforcement_attestation:egress(),now:NOW}).code,'KILL_SWITCH')})
test('typed actions reject surprise fields, raw recipients and invalid hashes',()=>{const good={message_id:'msg1',recipient_refs:['party-1'],subject_hash:H,body_hash:H2,resource_version:'v1'};assert.equal(validateActionPayload('send_email',good).valid,true);assert.equal(validateActionPayload('send_email',{...good,bcc:'attacker'}).valid,false);assert.equal(validateActionPayload('send_email',{...good,recipient_refs:['evil@example.com']}).valid,false);assert.equal(validateActionPayload('send_email',{...good,body_hash:'not-a-hash'}).valid,false)})
test('shadow mode hard-locks outbound send even with valid approval',async()=>{const ks=keyStore(),payload={message_id:'msg1',recipient_refs:['party-1'],subject_hash:H,body_hash:H2,resource_version:'v1'},cap=issueActionApproval({identity_assertion:identity(),key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'send_email',payload,policy_version:'legal-v2',expires_at:'2026-09-02T12:03:00Z',private_key:approver.privateKey,key_id:'approval-1',now:NOW});const r=await executeApprovedAction({capability:cap,identity_assertion:identity(),key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'send_email',payload,policy_version:'legal-v2',runtime_state:state,deployment_mode:'shadow',replay_store:{durable:true,atomic:true,claim:async()=>true},action_handler:async()=>({ok:true}),now:NOW});assert.equal(r.code,'SHADOW_LOCK')})
test('production action requires durable atomic replay store and executes once under 100-way replay',async()=>{const ks=keyStore(),payload={task_id:'t1',resource_version:'v7'},cap=issueActionApproval({identity_assertion:identity(),key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'complete_task',payload,policy_version:'legal-v2',expires_at:'2026-09-02T12:03:00Z',private_key:approver.privateKey,key_id:'approval-1',now:NOW});let executions=0;const used=new Set(),replay_store={durable:true,atomic:true,claim:async({idempotency_key})=>{if(used.has(idempotency_key))return false;used.add(idempotency_key);return true}},base={capability:cap,identity_assertion:identity(),key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'complete_task',payload,policy_version:'legal-v2',runtime_state:state,deployment_mode:'production',action_handler:async()=>{executions++;return{ok:true}},now:NOW};assert.equal((await executeApprovedAction(base)).code,'REPLAY_STORE_REQUIRED');const results=await Promise.all(Array.from({length:100},()=>executeApprovedAction({...base,replay_store})));assert.equal(results.filter(r=>r.executed).length,1);assert.equal(executions,1)})
test('approval binds resource version/exact payload and demands recent step-up auth',async()=>{const ks=keyStore(),payload={task_id:'t1',resource_version:'v7'},cap=issueActionApproval({identity_assertion:identity(),key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'complete_task',payload,policy_version:'legal-v2',expires_at:'2026-09-02T12:03:00Z',private_key:approver.privateKey,key_id:'approval-1',now:NOW}),replay_store={durable:true,atomic:true,claim:async()=>true};const changed=await executeApprovedAction({capability:cap,identity_assertion:identity(),key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'complete_task',payload:{task_id:'t1',resource_version:'v8'},policy_version:'legal-v2',runtime_state:state,deployment_mode:'production',replay_store,action_handler:async()=>({ok:true}),now:NOW});assert.equal(changed.code,'APPROVAL_MISMATCH');assert.throws(()=>issueActionApproval({identity_assertion:identity({auth_time:'2026-09-02T11:30:00Z'}),key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'complete_task',payload,policy_version:'legal-v2',expires_at:'2026-09-02T12:03:00Z',private_key:approver.privateKey,key_id:'approval-1',now:NOW}),/step-up/)})
test('provider transfer classification is explicit and policy version rotation revokes old approvals',async()=>{const missing=passport({third_country:undefined});assert.equal(authorizeLegalEgress({identity_assertion:identity(),request:request(),provider_passport:missing,key_store:keyStore(),runtime_state:state,network_probe:probe,egress_enforcement_attestation:egress(),now:NOW}).code,'PROVIDER_DENIED');const ks=keyStore(),payload={task_id:'t1',resource_version:'v7'},cap=issueActionApproval({identity_assertion:identity(),key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'complete_task',payload,policy_version:'legal-v2',expires_at:'2026-09-02T12:03:00Z',private_key:approver.privateKey,key_id:'approval-1',now:NOW});const rotated={...state,policy_version:'legal-v3'};const r=await executeApprovedAction({capability:cap,identity_assertion:identity(),key_store:ks,tenant_id:'tenant-a',matter_id:'m1',action:'complete_task',payload,policy_version:'legal-v3',runtime_state:rotated,deployment_mode:'production',replay_store:{durable:true,atomic:true,claim:async()=>true},action_handler:async()=>({ok:true}),now:NOW});assert.equal(r.code,'APPROVAL_MISMATCH')})
test('egress release gate needs fresh separately signed infrastructure proof',()=>{const missing=authorizeLegalEgress({identity_assertion:identity(),request:request(),provider_passport:passport(),key_store:keyStore(),runtime_state:state,network_probe:probe,now:NOW});assert.equal(missing.code,'EGRESS_ENFORCEMENT_DENIED');const forged=signEnvelope({body:{schema:'trustready-egress-enforcement-v1',tenant_id:'tenant-a',policy_version:'legal-v2',deny_by_default:true,only_gateway:true,observed_at:'2026-09-02T12:00:00Z',expires_at:'2026-09-02T12:04:00Z'},private_key:approver.privateKey,key_id:'approval-1',purpose:'egress_enforcement'});assert.equal(authorizeLegalEgress({identity_assertion:identity(),request:request(),provider_passport:passport(),key_store:keyStore(),runtime_state:state,network_probe:probe,egress_enforcement_attestation:forged,now:NOW}).code,'EGRESS_ENFORCEMENT_DENIED')})
