import { sha256 } from '../core/trust-kernel.mjs'

export const URL_PUBLIC_COLLECTOR_VERSION = 'url-public-v1'

function addDays(date, days) {
  return new Date(date.getTime() + days * 24 * 60 * 60 * 1000).toISOString()
}

function cleanHtml(html) {
  return String(html || '').replace(/<script[\s\S]*?<\/script>/gi, ' ').replace(/<style[\s\S]*?<\/style>/gi, ' ').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim()
}

function explicitAiDisclosure(value) {
  const text = value.toLowerCase()
  return [
    'you are interacting with an ai',
    'you are chatting with an ai',
    'this is an ai assistant',
    'responses are generated by ai',
    'ai-generated response',
  ].some((phrase) => text.includes(phrase))
}

function evidence({ subjectId, controlId, url, body, observedAt, note, ruleId }) {
  return {
    evidence_id: `ev-${sha256({ subjectId, controlId, url, body: sha256(body), observedAt: observedAt.toISOString(), ruleId }).slice(0, 24)}`,
    type: 'runtime_http_observation',
    strength: 'E3',
    observed_at: observedAt.toISOString(),
    valid_until: addDays(observedAt, 14),
    sha256: sha256(body),
    control_ids: [controlId],
    source: url,
    independent: true,
    candidate: false,
    note,
    provenance: {
      subject_id: subjectId,
      source_url: url,
      source_revision: `http-observation:${observedAt.toISOString()}`,
      content_sha256: sha256(body),
      collector_version: URL_PUBLIC_COLLECTOR_VERSION,
      promotion_rule_id: ruleId,
      promotion_ruleset_version: 'url-observation-rules-2026.08.1',
    },
  }
}

export async function collectPublicUrlEvidence(inputUrl, { fetchImpl = globalThis.fetch, observedAt = new Date(), subjectId = null } = {}) {
  if (typeof fetchImpl !== 'function') throw new TypeError('fetch implementation is required')
  const url = new URL(inputUrl)
  if (!['http:', 'https:'].includes(url.protocol)) throw new TypeError('Only http(s) URLs are supported')
  const canonical = url.toString()
  const id = subjectId || url.hostname
  const response = await fetchImpl(canonical, { redirect: 'follow', headers: { 'user-agent': 'trustready-scanner' } })
  if (!response.ok) throw new Error(`URL observation failed (${response.status}) for ${canonical}`)
  const html = await response.text()
  const visibleText = cleanHtml(html)
  const evidenceItems = []

  if (explicitAiDisclosure(visibleText)) {
    evidenceItems.push(evidence({
      subjectId: id,
      controlId: 'TR-AI-003',
      url: response.url || canonical,
      body: html,
      observedAt,
      note: 'Explicit user-facing AI disclosure was externally observed in the deployed page response.',
      ruleId: 'url.ai-disclosure-visible.v1',
    }))
  }

  return {
    subject: { id, url: response.url || canonical },
    observed_at: observedAt.toISOString(),
    collector_version: URL_PUBLIC_COLLECTOR_VERSION,
    evidence: evidenceItems,
    observations: {
      final_url: response.url || canonical,
      status: response.status,
      content_sha256: sha256(html),
      explicit_ai_disclosure: evidenceItems.some((item) => item.control_ids.includes('TR-AI-003')),
    },
    boundary: 'A public URL observation proves only what was externally observable in that response at that time. It does not prove hidden configuration, internal policy, identity, tenant isolation, deletion, monitoring or incident-response controls.',
  }
}
